### ISSUE TITLE
It would be nice with some documentation what this plugin does

### ISSUE THREAD

**Issue by PhroZenOne** [JetBrains/RiderSourceCodeAccess#4]
Just some feedback for your consideration:

1. Why should I add it, what functionality does it enable? 
2. How does it differ from RiderLink that the IDE installs? And why is this a separate plugin?
3. The description for this project is 

        Plugin for UE4 to user Rider for Unreal Engine as code editor
    I think the correct title should be

        Plugin for UE4 to use "Rider for Unreal Engine" as code editor
    And maybe expand on what you mean with "as code editor" (see point 1).
4. The README.md lists three different ways to install the plugin but does not really explain what the difference is here, what does an "Engine project" refer to? I assume you mean: "Installing the plugin globally in the engine instead of per project". And if that is the case, there is no difference in file structure when compiling the engine from source vs downloading the binaries, both have the Plugins folder under the Engine folder so no need to differentiate between a engine compiled from sources vs the binaries downloaded from the store. 

Cheers!

**Comment by DecoyRS** [comment]
Thank you for the feedback!
1. I will provide more details shortly, but this page is not considered to be the main entry point for the plugin. Official Epic Games marketplace is the right one:
https://www.unrealengine.com/marketplace/en-US/product/rider-source-code-access
2. There's close to 0 chanes that we will be able put RiderLink into Unreal Engine source code, plus RiderLink plugin for UE and UnrealLink plugin for Rider should be in synс with each other, so It's easier to bundle correct versions with Rider than support 2 different versions in 2 products. On the other hand, RiderSourceCodeAccess is the same breed as CLionSourceCodeAccess, VisualStudioSourceCodeAccess, etc, and therefore can be integrated in UE itself. And starting with UE 4.25 it is already bundled into Unreal Engine.
3. I will provide more details, thank you, but in the timely manner (see point 1)
4. There is a huge difference between adding plugin to Engine built from source and Engine downloaded from EGS. I have explicitely separated them because I have lost count how many times people have droped the plugin into the root folder of Engine from EGS and asked me "why it's not working".

**Comment by PhroZenOne** [comment]
Thanks for the info! This github repo was linked somewhere when installing Rider so I was a bit confused by the state of this repo with regards to documentation if this was supposed to be an official way to install it. But with it being bundled with 4.25 then this seems more reasonable.

And it being bundled means point 4 is not really needed to be clarified either, but I am a bit curious, my paths look like this:

     Downloaded with EGS: V:\UE_4.24\Engine\Plugins\Developer

     Source from github:  V:\UnrealEngineSource\Engine\Plugins\Developer

So for 4.24 at least, the paths seems to be the same but I am probably missing something. :)
